version: "2"

services:
  web:
    image: ${WEB_SERVER_IMAGE}
    ports:
      - ${WEB_SERVER_PORT_MAP}
    links:
      - php
    volumes_from:
      - app
    volumes:
      - ${WEB_SERVER_CONFIG_VOLUMES_MAP}
    networks:
      - appnet

  php:
    image: ${PHP_IMAGE}
    expose:
      - 9000
    links:
      - database
    volumes_from:
      - app
    networks:
      - appnet

  app:
    image: tianon/true
    volumes:
      - ${APP_VOLUME_MAP}
    networks:
      - appnet

  database:
    image: ${DB_SERVER}:${DB_SERVER_VERSION}
    volumes:
      - data:${DB_SERVER_CONTAINER_WORK_DIR}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
