version: "2"

services:
  web:
    build: ./build/${WEB_SERVER}/${WEB_SERVER_VERSION}
    ports:
      - ${WEB_SERVER_HOST_PORT}:80
    links:
      - php
    volumes_from:
      - app
    networks:
      - appnet

  php:
    build: ./build/php/${PHP_VERSION}
    expose:
      - 9000
    links:
      - database
    volumes_from:
      - app
    networks:
      - appnet

  app:
    image: tianon/true
    volumes:
      - ./:${APP_CONTAINER_DIR}
    networks:
      - appnet

  database:
    image: ${DB_SERVER}:${DB_SERVER_VERSION}
    volumes:
      - data:${DB_SERVER_CONTAINER_WORK_DIR}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"
