version: "2"

services:

  app_code:
    image: tianon/true
    volumes:
      - ${APP_CODE_VOLUME_MAP}
    networks:
      - app_network

  http:
    image: ${HTTP_IMAGE}
    ports:
      - ${HTTP_PORT_MAP}
    links:
      - php
    volumes_from:
      - app_code
    volumes:
      - ${HTTP_CONFIG_VOLUMES_MAP}
    networks:
      - app_network

  php:
    image: ${PHP_IMAGE}
    expose:
      - 9000
    links:
      - database
      - app_cache
    volumes_from:
      - app_code
    networks:
      - app_network

  database:
    image: ${DATABASE_IMAGE}
    volumes:
      - ${DATABASE_VOLUME_MAP}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app_network
  
  app_cache:
    image: ${APP_CACHE_IMAGE}
    networks:
      - app_network
  
  dev_cli:
    image: ${DEV_CLI_IMAGE}
    links:
      - database
    volumes_from: 
      - app_code
    networks: 
      - app_network


networks:
  app_network:
    driver: "bridge"

volumes:
  data:
    driver: "local"
