version: "2.1"

services:

  ##################
  #   PRODUCTION   #
  ##################

  code:
    image: tianon/true
    volumes:
      - ${HOST_CODE_DIR:-./}:${CONTAINER_CODE_DIR:-/var/www}
    networks:
      - app_network

  cache:
    build: ${CACHE_IMAGE_BUILD_DIR:-./docker/cache/redis/build}
    image: ${CACHE_IMAGE:-redis:latest}
    ports:
      - ${CACHE_PORTS_MAP:-6379:6379}
    healthcheck:
      test: "exit 0"
    networks:
      - app_network

  cron-jobs:
    build: ${CRON_JOBS_IMAGE_BUILD_DIR:-./docker/cron-jobs/php7-fpm/build}
    image: ${CRON_JOBS_IMAGE:-exadra37/php7-fpm:latest}
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
      logger:
        condition: service_healthy
      queue:
        condition: service_healthy
    volumes_from:
      - code
    networks:
      - app_network

  database:
    build: ${DATABASE_IMAGE_BUILD_DIR:-./docker/database/percona/build}
    image: ${DATABASE_IMAGE:-percona:latest}
    healthcheck:
      test: "exit 0"
    volumes:
      - ${DATABASE_VOLUME_MAP:-~/.dockerize/services/database/volumes/mysql:/var/lib/mysql}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-rootsecret}
      MYSQL_DATABASE: ${DB_DATABASE:-dockerstack}
      MYSQL_USER: ${DB_USERNAME:-dockerstack}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - app_network

  http:
    build: ${HTTP_IMAGE_BUILD_DIR:-./docker/http/nginx/build}
    image: ${HTTP_IMAGE:-exadra37/nginx:latest}
    ports:
      - ${HTTP_PORT_MAP:-80:80}
    depends_on:
      php:
        condition: service_healthy
    volumes:
      - ${HTTP_CONFIG_VOLUME_MAP:-./docker/http/nginx/build/conf.d:/etc/nginx/conf.d}
    volumes_from:
      - code
    networks:
      - app_network

  logger:
    build: ${LOGGER_IMAGE_BUILD_DIR:-./docker/logger/elasticsearch/build}
    image: ${LOGGER_IMAGE:-elasticsearch:latest}
    healthcheck:
      test: "exit 0"
    ports:
      - ${LOGGER_HTTP_PORT_MAP:-9200:9200}
    environment:
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=1gb
    volumes:
      - ${LOGGER_VOLUME_MAP:-~/.dockerize/services/logger/volumes/elasticsearch:/usr/share/elasticsearch/data}
    networks:
      - app_network

  monitor:
    build: ${MONITOR_IMAGE_BUILD_DIR:-./docker/monitor/kibana/build}
    image: ${MONITOR_IMAGE:-kibana:latest}
    healthcheck:
      test: "exit 0"
    ports:
      - ${MONITOR_HTTP_PORT_MAP:-5601:5601}
    environment:
      ELASTICSEARCH_URL: ${MONITOR_LOGGER_URL:-http://logger:9200}
    depends_on:
      logger:
        condition: service_healthy
    networks:
      - app_network

  php:
    build: ${PHP_IMAGE_BUILD_DIR:-./docker/php/php7-fpm/build}
    image: ${PHP_IMAGE:-exadra37/php7-fpm:latest}
    working_dir: ${CONTAINER_CODE_DIR:-/var/www}
    expose:
      - 9000
    healthcheck:
      test: "exit 0"
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
      monitor:
        condition: service_healthy
      queue:
        condition: service_healthy
    volumes:
      - ${PHP_INI_VOLUME_MAP:-./docker/php/php7-fpm/php.ini:/usr/local/etc/php.ini}
    volumes_from:
      - code
    networks:
      - app_network

  queue:
    build: ${QUEUE_IMAGE_BUILD_DIR:-./docker/queue/beanstalkd/build}
    image: ${QUEUE_IMAGE:-schickling/beanstalkd:latest}
    healthcheck:
      test: "exit 0"
    volumes_from:
      - code
    networks:
      - app_network


  ###################
  #   DEVELOPMENT   #
  ###################

  dev-cli:
    build: ${DEV_CLI_IMAGE_BUILD_DIR:-./docker/dev-cli/php7/build}
    image: ${DEV_CLI_IMAGE:-exadra37/php7-dev-cli:latest}
    working_dir: ${CONTAINER_CODE_DIR:-/var/www}
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
      monitor:
        condition: service_healthy
      queue:
        condition: service_healthy
    volumes:
      - ${DEV_CLI_SSH_VOLUME_MAP:-~/.ssh:/home/php-fpm/.ssh}
      - ${DEV_CLI_GIT_CONFIG_VOLUME_MAP:-~/.gitconfig:/home/php-fpm/.gitconfig}
    volumes_from:
      - code
    networks:
      - app_network

  database-cli:
    build: ${DATABASE_CLI_IMAGE_CONTEXT:-./docker/database-cli/mycli/build}
    image: ${DATABASE_CLI_IMAGE:-exadra37/mycli:latest}
    networks:
      - app_network
    depends_on:
      database:
        condition: service_healthy
    command: "--host database"

  cache-cli:
    build: ${CACHE_CLI_IMAGE_BUILD_CONTEXT:-./docker/cache-cli/redis/build}
    image: ${CACHE_IMAGE:-redis:latest}
    healthcheck:
      test: "exit 0"
    networks:
      - app_network
    entrypoint: ${CACHE_CLI_ENTRYPOINT:-redis-cli -h cache}

networks:
  app_network:
    driver: "bridge"
